### PR TITLE
Fix/missing functions

### PR DESCRIPTION
**Pull request by andrewbenton**
Added some missing functions for SDL's surface and window

surface:
- setColorKey

window:
-get/set MinimumSize
-get/set MaximumSize
-getWindowDisplayMode

### CODE REVIEW

**Comment by p0nce** [comment]
I'll look at it later.

**Comment by p0nce** [comment]
Thanks you! High-quality PR.

**Comment by p0nce** [comment]
Use  v6.1.3

**Comment by ZombineDev** [comment]
Thanks @andrewbenton and @p0nce. I was just about to use `window.get/setMin/MaxSize` so this PR had perfect timing ;)

**Pull request merged**
