### PR TITLE
Add convenience functionality for using Box like a Rectangle

### PR DESCRIPTION
**Pull request by ahmetsait**
This PR adds:
- Setters for width, height, size properties
- Dimension-wise abs / sort functions (see: isSorted)
- ~~Left, right, top, bottom properties~~
- ~~x & y properties (preserves the width & height)~~

into Box that make Rectangle-like usage smoother. Nothing fancy, will do the unit tests if these changes are welcome.

### CODE REVIEW

**Comment by p0nce** [comment]
This is generally a good idea to make GFM more friendly.
The only constraint is it must unambiguous.
I'm not sold on the idea of `r.x = 14;` since unless reading the doc you don't know if this also change width or not.
The current situation is `r.min.x = 14;` which somehow makes it clear only the "min" point changes.

Also having both `.x` and `.left` is not very much welcome. In this case they are different and it will create confusion. The one that preserve width is .x while in CSS it would be .left

Other than that good ideas that I think will implement using your PR as an inspiration.

Also not sure if I'm sold on `front` and `back` since for example in OpenGL front will be positive Z, and back negative Z, and that changes across APIs.

https://docs.godotengine.org/fr/stable/classes/class_rect2.html

So this really need to be a careful change.

**Comment by p0nce** [comment]
It's pretty clear to me that GFM is quite bad with readability. The goal was to have as much types as possible being generic and keep the code short. This ended being false goals, readability matters a lot more.

**Comment by ahmetsait** [comment]
So the idea was that a Rectangle data type usually consists of (x, y, w, h) where (x, y) is upper-left point and (w, h) is the size where if you add point and size together you get bottom-right point. This is similar to [SDL](https://wiki.libsdl.org/SDL_Rect), [.Net](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.rectangle) and [Godot](https://docs.godotengine.org/en/stable/classes/class_rect2.html).

The left-top-right-bottom convention supposed to be modeled based on these APIs:

https://docs.microsoft.com/en-us/windows/win32/api/windef/ns-windef-rect
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.rectangle

However, this PR assumes +Y is upwards and +Z is backwards similar to OpenGL.

> [LearnOpenGL](https://learnopengl.com/Getting-started/Coordinate-Systems):
> By convention, OpenGL is a right-handed system. What this basically says is that the positive x-axis is to your right, the positive y-axis is up and the positive z-axis is backwards. Think of your screen being the center of the 3 axes and the positive z-axis going through your screen towards you.

So you're completely right about ambiguity and it seems to me that a separate Rectangle(T) would probably be a much better way to design and make semantics clear in that sense. Main reason I made this PR was to discuss a proper way to do it without a big diff.

So the question is should I make another PR that adds a separate Rectangle implementation?
Also, I can strip this PR down to `sort()` only since that feels like a worthwhile addition still.

**Comment by p0nce** [comment]
What I propose to do (I will do it, or will merge it if you'd prefer) is to add:

- size setter (not sure if this one can work, it fail unittest here)
- width setter
- height setter
- depth setter
- left getter/setter, preserve width like a CSS rule would
- right getter/setter, preserve width like a CSS rule would
- top getter/setter, preserve height, CSS order (origin is top-left)
- bottom getter/setter, preserve height, CSS order (origin is top-left)

None of these need to assume a particular sorting with `isSorted`.
I would rather decide to leave out "x", "y", "z", "front" and "back" because of ambiguity.

What do you think?

**Comment by p0nce** [comment]
And about a `Rectangle`, not only I completely agree but I think GFM should be deprecated one day in favor of a more Godot-like API with actual friendly names and good APIs.

Without being generic too much it could provide:

Vector2
Vector3
Vector4
Transform
Rectangle
AABB

Right now, we are not reaping any benefits from genericity as the code compiles slowly and the API is worse because of genericity.

**Comment by ahmetsait** [comment]
> - `size` setter (not sure if this one can work, it fail unittest here)
> - `width` setter
> - `height` setter
> - `depth` setter
> - `left` getter/setter, preserve width like a CSS rule would
> - `right` getter/setter, preserve width like a CSS rule would
> - `top` getter/setter, preserve height, CSS order (origin is top-left)
> - `bottom` getter/setter, preserve height, CSS order (origin is top-left)
> 
> What do you think?

Well, as far as the rabbit hole goes, width, height etc. are also not exactly unambiguous (how about pivoting from center?) and also, [RECT](https://docs.microsoft.com/en-us/windows/win32/api/windef/ns-windef-rect) struct in WinAPI has `left, right` fields so naturally modifying them individually does not preserve width for example.

So I don't have a definitive conclusion ¯\\\_(ツ)\_/¯. If you still want the changes you listed, let me know. Or I can drop this and make a simple Rectangle PR if you wish.

**Comment by p0nce** [comment]
Mmmm. You are right. Which was the function you have needed in your GFM usage ? that prompted the PR.

**Comment by ahmetsait** [comment]
I was doing experimental hobby stuff as I find some time from school and I had SDL window related code like this:
```d
Rectangle!int bounds() @property;
Rectangle!int bounds(Rectangle!int value) @property;
Size!int maxSize() @property;
Size!int maxSize(Size!int value) @property;
```
I thought "Didn't gfm.math already have these?" so I tried to use vec2i & box2i and then realized it is rather inconvenient to do so I decided there is some room for improvement and here we are.

I should mention that I actually like the generic style of current gfm. Having one unified matrix implementation instead of [this](https://github.com/opentk/opentk/tree/4.4.0/src/OpenTK.Mathematics/Matrix) kind of boilerplate is a good thing in my opinion. Maybe the `generateLoopCode` mixins can be refactored into something that compiles faster but I suppose you tried that already.

> Transform (a better name than mat4f)
> Rectangle (a better name than box2)
> AABB (a better name than box3)

Just a heads up, Transform is not exactly the same thing as a 4x4 matrix, game engines [usually store](https://gamedev.stackexchange.com/questions/175006/storing-transformations-in-game-objects-glm-c) translation, rotation and scale individually and then generate a matrix from these on demand because decomposing TRS back from matrix [has some issues](https://computergraphics.stackexchange.com/questions/4491/detect-a-lossy-matrix-decomposition).

I've seen BBox name [in the wild](https://github.com/mattleibow/jitterphysics/blob/master/source/Jitter/LinearMath/JBBox.cs#L36) as well but this is kinda getting into bike shedding territory.

**Comment by p0nce** [comment]
> I should mention that I actually like the generic style of current gfm. Having one unified matrix implementation instead of this kind of boilerplate is a good thing in my opinion.

Yes, for this case it isn't bad, but it could have a better separation what is "API surface" and the details of implementation.
For gamedev, you might only need a 4x4, 4x3, and 3x3 (possible 3x2) matrix realistically.
Over the years I've been a bit wary of having generic code and generic names since it seems they lead to a poorer end-user experience.

**Comment by p0nce** [comment]
So... how about:

- `size` setter (not sure if this one can work, it fail unittest here)
- `width` setter
- `height` setter
- `depth` setter

Taking min as pivot. I would definately merged that if the unittest pass.

**Comment by ahmetsait** [comment]
Will do 👍

**Comment by p0nce** [comment]
Looks Cool To Me

**Comment by p0nce** [comment]
This is in v8.0.5

**Comment by p0nce** [comment]
What would you think about a new library that would copy the API of Godot?

With `Vector2`, `Vector3`, `Vector4`, `Basis`, `Transform`, etc.

I'm becoming a big fan of stealing APIs so that you can just link to their documentation.

**Comment by ahmetsait** [comment]
I personally haven't used Godot, but it all depends on what you want to achieve. From what I can see Godot has a focused goal of trying to be an easy to use game engine which may or may not be in line with yours.

As I said before, things like `Transform` are not meant to replace `mat4f`, but rather built from it. I see gfm.math as something akin to [OpenTK.Mathematics](https://github.com/opentk/opentk/tree/master/src/OpenTK.Mathematics) which makes perfect sense to me, I don't know about how or why others don't find the API intuitive. Then again, I might not be representing the majority so  ¯\\\_(ツ)\_/¯

**Pull request merged**
