### PR TITLE
Add simple joystick interface

### PR DESCRIPTION
**Pull request by andrewbenton**
This could do with more testing, but it's mostly punch-through
functionality.

### CODE REVIEW

**Comment by p0nce** [comment]
LGTM.
To be consistent I guess it should take a `gfm.sdl2.sdl.SDL2` object too.

**Comment by andrewbenton** [comment]
I thought about that, but since it wasn't necessary, I skipped it.  On a second look, I like the idea of having access to the logger.  I'll toss that in later when I get time.

**Comment by p0nce** [comment]
It's not a fantastic design, and maybe I'll remove it at one point, but this allows things like that (and context-wide things in OpenGL) so for now let's follow it!

**Comment by andrewbenton** [comment]
I actually prefer having that to not.  It ensures that you have SDL2 initialized.

**Comment by p0nce** [comment]
Available as of v6.2.0

**Pull request merged**
