### PR TITLE
[WIP] Simplify gfm:math

### PR DESCRIPTION
**Pull request by ahmetsait**
The purpose of this PR is to simplify gfm:math code for potentially improving compile times and making the code easier read by stripping unnecessary template instantiations and CTFE usage.

- [ ] Vector
- [ ] Box
- [ ] Matrix
- [ ] Quaternion

Feedback welcome.

### CODE REVIEW

**Comment by p0nce** [comment]
Looks good, but. How is the right opDispatch called? 
The goal was to have .rgba or .xyzw but not .xyba
It looks like the opDispatch will conflict? Or is it a sort of SFINAE?

**Comment by ahmetsait** [comment]
Heh, I realized it a bit late that opDispatch doesn't work in this state. I will probably merge the functions. I might take a while to get to it tho.

**Comment by ahmetsait** [comment]
@p0nce I will consider Vector part done after you approve the changes.
Tests passing on my system. Let's see what CI is up to.

**Comment by ahmetsait** [comment]
Now the question is... Does it actually compile faster? Getting rid of a bunch of ctfe string builder usage seemed like a good bet, but I can't reliably measure the difference now (and dub is also somewhat unreliable).
I might ask about how to profile compilation times to understand things better.

**Comment by p0nce** [comment]
Getting on this.
The travis CI is super broken usually, here it's downloading the things.

I see good things in this PR, however 
`mixin(generateLoopCode!("v[@] = arr[@];", N)());` is here because it's the fastest way on both DMD and LDC, whatever the optimization settings.
So I'm really worried of letting this go, twice I've measured the runtime cost and it was fine.
So at least 20d9d23 should be reverted.

**Comment by ahmetsait** [comment]
And just like that, profilers showed how such a fool I was, proving that I know nothing about computers once again.
Turns out the reason for compile times were mostly because of phobos' std.format (and my std.algorithm usage which made it even slower).

This is current master (3.47s total):
Tracy Profiler Output 1

And this is what I get after b98236f (924.28ms total):
Tracy Profiler Output 2

**Comment by p0nce** [comment]
LDC 1.23 + optimizations => same perf than before
image

DMD v2.095 + optimizations => slighty worse than before
image

LDC 1.23 in debug mode => **2x slower** than before
image

DMD v2.095 in debug mode => worse than before
image


On this machine I cannot reproduce the compile speed enhancement, but this machine is pretty fast.

To be merged this needs to:
- not make things slower
- rebase

**Comment by ahmetsait** [comment]
I'll try to look into the performance regression today 👍

**Comment by ahmetsait** [comment]
Alright things getting busy again can't promise much...

**Pull request closed without merging**
