### PR TITLE
First attempt at improved toString for wideint.

### PR DESCRIPTION
**Pull request by quickfur**
Here's my attempt at improving `toString`. It supports the `%s`, `%d` (both decimal) and `%x` (hex) output formats.

We use a non-allocating overload for `toString` that spools its data via a caller-provided delegate, so that we don't have to allocate an output string.

The decimal formatting code also uses an on-stack buffer for storing the output digits so that we don't have to allocate. The buffer size is designed to be just a slight overestimate of the longest possible decimal representation of an n-bit number (see in-code comments), and digits are written in reverse order of extraction, so that we don't have to depend on ugly things like `std.algorithm.reverse`, which is actually throwing (because of stupid autodecoding).

Despite all of this, however, because of a silly limitation in current versions of Phobos we cannot actually mark `toString` as `pure nothrow @nogc`. Basically, the `scope void delegate` argument is, by default, assumed to be impure, throwing, and allocating, even if you pass in something that's pure, nothrow, and `@nogc`. We can't mark the argument with these qualifiers because it might break callers who need to, e.g., write to stdout (e.g., `writeln`).  The latest compiler *does* give us a way out, by templatizing `toString` into:
````
void toString(T : void delegate(const(char)[]))(scope T sink, FormatSpec!char fmt)
````
This overload, being a template, will trigger attribute inference and the compiler will correctly infer `pure`, `nothrow`, `@nogc`, etc., where appropriate.

**However,** the sad thing is, the current version of `std.format` does not recognize this overload of `toString`, so `format()` won't actually call `toString`, which defeats the entire purpose of this exercise. So unfortunately, we have to leave `toString` without `pure nothrow @nogc` for now.

I also tried to eliminate the dependency on `std.format`, but couldn't because although the docs on `dlang.org` claim that `toString` can take a string argument for format specifier instead of `FormatSpec`, I couldn't get `std.format` to actually recognize any such overload. So there's no way to get rid of the `std.format` import line, which may cause binary bloat in some cases. Hopefully this is not a show-stopper.

### CODE REVIEW

**Comment by quickfur** [comment]
How do I reset the Travis CI tester? It seems to have failed on an unrelated intermittent server failure when trying to download Derelict.

**Comment by JakobOvrum** [comment]
> However, the sad thing is, the current version of std.format does not recognize this overload of `toString`, so `format()` won't actually call `toString`, which defeats the entire purpose of this exercise. So unfortunately, we have to leave `toString` without `pure nothrow @nogc` for now.

It's clunky but it works with the right incantations; see for example [the new Tuple.toString](https://github.com/D-Programming-Language/phobos/pull/3833/files#diff-4e008aedb3026d4a84f58323e53bf017R843). Did you remember to mark it `const`?

**Comment by quickfur** [comment]
Thanks for the tip, it actually works now!!!!  Hooray! (Now hoping it won't break on older versions of dmd in the Travis CI tester...)

**Comment by p0nce** [comment]
Good.

**Pull request merged**
