### PR TITLE
Add `Vector.opCmp`

### PR DESCRIPTION
**Pull request by chances**

### CODE REVIEW

**Comment by p0nce** [comment]
Hello,

What does this enable? I guess insertion in a map?


I think your implementation fails with `vec2i(0, 1) != vec2i(1, 0)`.

Perhaps it should be:
```
                if (v[i] > other.v[i])
                    difference += (N-1-i);
                else if (v[i] < other.v[i])
                    difference += -(N-1-i);
```
in order for the first dimension to count more then the second in comparisons.

**Comment by chances** [comment]
@p0nce I needed to compare vectors, i.e. `vec2f(10, 8) < vec2f(7, 0)`.

All of the unit tests pass locally on my machine. 🤷️

**Comment by p0nce** [comment]
With your implementation, vec2i(0, 1) is equal to vec2i(1, 0)

**Comment by p0nce** [comment]
Closing.
I'll consider merging if there were
1. an implementation with same semantics that slice comparison,
2. a use case.

**Pull request closed without merging**
