### PR TITLE
Fix Vector constructor accepting too many arguments

### PR DESCRIPTION
**Pull request by Yoplitein**
This fixes the case of `vec2f(1, 2, 3)`.

### CODE REVIEW

**Comment by Yoplitein** [comment]
Now `vec2f(vec2f(1, 2), 3)` is also handled.

**Comment by p0nce** [comment]
Good job.

**Comment by p0nce** [comment]
Use v3.0.7+

**Comment by Yoplitein** [comment]
> Good job.

Thanks!

**Pull request merged**
