### PR TITLE
Example of 3D picking added.

### PR DESCRIPTION
**Pull request by drug007**

### CODE REVIEW

**Comment by p0nce** [comment]
Won't merge. This is too similar to simpleshader, and I do not wish to maintain similar examples. I use to have another OpenGL example, but this create work when the API changes.

More over, picking through glReadPixels stalls the pipeline. It is my opinion it should be done with raycasting in the scene instead.

**Comment by drug007** [comment]
Similarity was intended - it's simple for people to go through similar examples that differ only in several details but have different functionality. What about `glReadPixels` - yes, it's stalls, just its tutorial was found before ray casting picking and it works fine for me.

**Comment by p0nce** [comment]
GFM's examples goal is to demonstrate GFM features not OpenGL specific techniques. So there isn't a picking example for the same reason there isn't a deferred rendering example or a shadow mapping example.

The problem with making OpenGL tutorials is that it is a lot of maintenance work (and I'm very busy with my business), more so than writing documentation so having only simpleshader was kind of intended even if lacking.
 
But I will consider the better names you found and perhaps that mutable FBO change (that isn't in your PR by the way :) ). `.use()` and `unuse()` are awful names.

**Comment by drug007** [comment]
ok.

**Pull request closed without merging**
