### PR TITLE
Added vector operations to static arrays

### PR DESCRIPTION
**Pull request by lablanu**
Implements the essential functions of the `Vector` struct, element access by name(see `defineFieldAccess`) and vector operations for static arrays.
With unit test.

### CODE REVIEW

**Comment by p0nce** [comment]
I feel like we had a giant misunderstanding: it was never my intention to have static arrays vector ops in GFM.

I encouraged you to do it because I find it interesting and worthwhile but essentially it is a different way of doing things, with different pluses and minuses. 

I have concerns with it:
- it is important to me that vector operations are fully @nogc nothrow and never, ever allocate
- I am concerned about the use of the short names "x", "y" and "z" in the global namespace, though D is pretty good with name conflicts
- not sure about array literals allocating, for example in your unittest

It is an interesting design, one that no-one has attempted so far, so I encourage you to create a new DUB package. Note that gfm:math was hurt a lot in adoption from being a sub-package relatively lost in another package.

If the approach reveals superior I'll be the first to deprecate my own Vector and use yours, but letting two competing abstractions next to each other just invite to use them both at the same time.

**Comment by lablanu** [comment]
Alright, I'll work on satisfying those concerns.

**Comment by p0nce** [comment]
I need to think about it more in the coming days. It could fit nicely in a gfm.math.staticarray module where we could investigate the implications in terms of name clashes.
And matrices could work with both vector types.

**Comment by p0nce** [comment]
The ideal scenario would be I believe:
- you make a DUB package for vectors, implemented as static arrays. As a separate package, it stands a chance to become popular and take the crown in the D-cosystem.
- you find a way to have static arrays literals without allocating (through an adhoc function, anything really)
- GFM makes a breaking change that alias vec4f to float[4]. Removes Vector from here.

**Pull request closed without merging**
